[phases.setup]
nixPkgs = ['nodejs_20', 'chromium', 'glib', 'nss', 'nspr', 'atk', 'at-spi2-atk', 'libdrm', 'expat', 'libxcb', 'libxshmfence', 'libX11', 'libXcomposite', 'libXdamage', 'libXext', 'libXfixes', 'libXrandr', 'libgbm', 'pango', 'cairo', 'alsa-lib']
